version: '3.7'

services:
  app:
    container_name: highres_seg_demo
    build: .
    command: 'gunicorn -b 0.0.0.0:8075 --reload app:server'
    environment:
      DATA_TILED_URI: '${DATA_TILED_URI}'
      DATA_TILED_API_KEY: '${DATA_TILED_API_KEY}'
      MASK_TILED_URI: '${MASK_TILED_URI}'
      MASK_TILED_API_KEY: '${TILED_API_KEY}'
      SEG_TILED_URI: '${SEG_TILED_URI}'
      SEG_TILED_API_KEY: '${SEG_TILED_API_KEY}'
      USER_NAME: '${USER_NAME}'
      USER_PASSWORD: '${USER_PASSWORD}'
      RESULTS_DIR: '${RESULTS_DIR}'
      PREFECT_API_URL: '${PREFECT_API_URL}'
      FLOW_NAME: '${FLOW_NAME}'
      TIMEZONE: "${TIMEZONE}"
    volumes:
      - ./app.py:/app/app.py
      - ./constants.py:/app/constants.py
      - ./callbacks:/app/callbacks
      - ./components:/app/components
      - ./utils:/app/utils
    ports:
      - '8075:8075'

#     networks:
#       - computing_api_default

# networks:
#   computing_api_default:
#     external: true
